version: '3.8'

services:
  master:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1qaz2wsx
    volumes:
      - ./data/postgres/master:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  slave:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1qaz2wsx
      POSTGRES_MASTER_SERVICE_HOST: master
    volumes:
      - ./data/postgres/slave:/var/lib/postgresql/data
    depends_on:
      - master
    ports:
      - "5433:5432"