version: '3.8'

x-postgres-common:
  &postgres-common
  image: postgres:latest
  healthcheck:
    test: ["CMD-SHELL", "pg_isready", "-U", "admin", "-d", "auth"]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  gateway:
    container_name: gateway
    image: reddtsai/reddservice-gateway:dev
    environment:
      - HTTP_PORT=80
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/app/conf.d
    depends_on:
      - auth-service

  auth-service:
    container_name: auth-service
    image: reddtsai/reddservice-auth:dev
    environment:
      - GRPC_PORT=50051
      - HTTP_PORT=8080
    ports:
      - "8081:8080"
    volumes:
      - ./conf.d:/app/conf.d
    depends_on:
      auth-db-master:
        condition: service_healthy
      auth-db-slave:
        condition: service_healthy

  auth-db-master:
    <<: *postgres-common
    container_name: auth-db-master
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1qaz2wsx
    volumes:
      - ./data/postgres/master:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  auth-db-slave:
    <<: *postgres-common
    container_name: auth-db-slave
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1qaz2wsx
    volumes:
      - ./data/postgres/slave:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      auth-db-master:
        condition: service_healthy


