version: '3.8'

x-postgres-common:
  &postgres-common
  image: postgres:latest

services:
  gateway:
    container_name: gateway
    image: reddtsai/reddservice-gateway:dev
    environment:
      - HTTP_PORT=80
    ports:
      - "18080:80"
    volumes:
      - ./conf.d:/app/conf.d
    depends_on:
      - auth-service

  auth-service:
    container_name: auth-service
    image: reddtsai/reddservice-auth:dev
    environment:
      - GRPC_PORT=50051
      - HTTP_PORT=8080
    ports:
      - "18081:8080"
    volumes:
      - ./conf.d:/app/conf.d
    depends_on:
      - auth-db-master
      - auth-db-slave

  auth-primary-db:
    <<: *postgres-common
    container_name: auth-primary-db
    environment:
      POSTGRES_DB: auth
      POSTGRES_PASSWORD: 1qaz2wsx
    volumes:
      - ./data/auth/primary:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  auth-replica-db:
    <<: *postgres-common
    container_name: auth-replica-db
    environment:
      POSTGRES_PASSWORD: 1qaz2wsx
    volumes:
      - ./data/auth/replica:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - auth-primary-db


