apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: reddservice-gateway
  namespace: reddservice
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reddservice-gateway-virtualservice
  namespace: reddservice
spec:
  hosts:
    - "*"
  gateways:
    - reddservice-gateway
  http:
    - match:
        - uri:
            exact: /v1/sign-up
      route:
        - destination:
            host: gateway-service
            port:
              number: 80
