apiVersion: v1
kind: Service
metadata:
  namespace: reddservice
  name: gateway-service
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: gateway

---
apiVersion: v1
kind: Service
metadata:
  namespace: reddservice
  name: auth-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: auth

---
apiVersion: v1
kind: Service
metadata:
  namespace: reddservice
  name: pgpool-service
spec:
  selector:
    app: pgpool
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: auth-virtualservice
  namespace: reddservice
spec:
  hosts:
    - "auth-service.reddservice.svc.cluster.local"
  http:
    - match:
        - port: 50051
      route:
        - destination:
            host: "auth-service.reddservice.svc.cluster.local"
            port:
              number: 50051

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: auth-destinationrule
  namespace: reddservice
spec:
  host: auth-service.reddservice.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN

---

