// Code generated by MockGen. DO NOT EDIT.
// Source: common.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/reddtsai/reddservice/api/proto"
)

// MockIGrpcClientConn is a mock of IGrpcClientConn interface.
type MockIGrpcClientConn struct {
	ctrl     *gomock.Controller
	recorder *MockIGrpcClientConnMockRecorder
}

// MockIGrpcClientConnMockRecorder is the mock recorder for MockIGrpcClientConn.
type MockIGrpcClientConnMockRecorder struct {
	mock *MockIGrpcClientConn
}

// NewMockIGrpcClientConn creates a new mock instance.
func NewMockIGrpcClientConn(ctrl *gomock.Controller) *MockIGrpcClientConn {
	mock := &MockIGrpcClientConn{ctrl: ctrl}
	mock.recorder = &MockIGrpcClientConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGrpcClientConn) EXPECT() *MockIGrpcClientConnMockRecorder {
	return m.recorder
}

// GetAuthClient mocks base method.
func (m *MockIGrpcClientConn) GetAuthClient() proto.AuthServiceClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthClient")
	ret0, _ := ret[0].(proto.AuthServiceClient)
	return ret0
}

// GetAuthClient indicates an expected call of GetAuthClient.
func (mr *MockIGrpcClientConnMockRecorder) GetAuthClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthClient", reflect.TypeOf((*MockIGrpcClientConn)(nil).GetAuthClient))
}
