CREATE TABLE IF NOT EXISTS users (
    "ID" SERIAL PRIMARY KEY,
    "NAME" VARCHAR(50) NOT NULL,
    "EMAIL" VARCHAR(256) NOT NULL,
    "PASSWORD" VARCHAR(256) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);