name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: build auth image
        run: docker build --platform linux/arm64 --build-arg APP_VERSION=${{ github.ref_name }} --build-arg CONFIG_PATH=conf.d -f deployments/docker/auth/Dockerfile -t reddtsai/reddservice-auth:${{ github.ref_name }} .
      - name: push auth image
        run: docker push reddtsai/reddservice-auth:${{ github.ref_name }}
      - name: build gateway image
        run: docker build --platform linux/arm64 --build-arg APP_VERSION=${{ github.ref_name }} --build-arg CONFIG_PATH=conf.d -f deployments/docker/gateway/Dockerfile -t reddtsai/reddservice-gateway:${{ github.ref_name }} .
      - name: push gateway image
        run: docker push reddtsai/reddservice-gateway:${{ github.ref_name }}
